In [1]:
#Nama : Rofifah Nurul Annisa
#No.Registrasi : 01123956260-7
#Latihan Numpy Menghitung BMI
import numpy as np

tinggi = []
berat = []
nama = []

a = int(input("Jumlah orang yang ingin diinput datanya :"))

for i in range(a):
    nama.append(input("Masukkan nama anda :"))
    berat.append(float(input("Masukkan berat anda (kg):")))
    tinggi.append(float(input("Masukkan tinggi anda (cm):")))
    
tinggi_np = np.array(tinggi)
berat_np = np.array(berat)



#diubah ke meter
tinggi_np = tinggi_np/100


BMI = np.array(berat_np / (tinggi_np**2))

for i in range (tinggi_np.size):
    print("================================")
    print("Nama : ", nama[i])
    print("Tinggi : ", tinggi[i])
    print("Berat : ", berat[i])
    status=""

    if BMI[i] < 18.4:
        status="Berat Badan Kurang"
    elif BMI[i] >= 18.5 and BMI[i] <= 24.9:
        status = "Berat Badan Ideal"
    elif BMI[i] >=25 and BMI[i] <=29.9 :
        status = "Berat Badan Lebih"
    elif BMI[i] >= 30 and BMI[i] <= 39.9:
        status ="Gemuk"
    else :
        status = "Sangat Gemuk"
    print("Nilai BMI : ", BMI[i])
    print("Status : ", status)


Jumlah orang yang ingin diinput datanya :2
Masukkan nama anda :Budi
Masukkan berat anda (kg):65
Masukkan tinggi anda (cm):160
Masukkan nama anda :Lulu
Masukkan berat anda (kg):48
Masukkan tinggi anda (cm):155
Nama :  Budi
Tinggi :  160.0
Berat :  65.0
Nilai BMI :  25.390624999999996
Status :  Berat Badan Lebih
Nama :  Lulu
Tinggi :  155.0
Berat :  48.0
Nilai BMI :  19.979188345473464
Status :  Berat Badan Ideal


In [2]:
#Tugas Latihan Numpy (Matriks)
import numpy as np
matriksA= np.random.randint(10,size = (2,3))
matriksB= np.random.randint(10,size = (3,3))

print("Matriks A : \n{}".format(matriksA))
print("Matriks B : \n{}".format(matriksB))

hasilKali = np.dot(matriksA,matriksB)
print("Hasil kalinya yaitu \n{}".format(hasilKali))

hasilKaliTranspose=np.transpose(hasilKali)
print("Hasil transposenya yaitu \n{}".format(hasilKaliTranspose))

ratarata = np.mean(hasilKaliTranspose)
print("Rata-ratanya yaitu: ",ratarata)

median = np.median(hasilKaliTranspose)
print("Mediannya yaitu:",median)

Matriks A : 
[[3 1 7]
 [5 1 4]]
Matriks B : 
[[5 9 3]
 [5 3 5]
 [4 8 2]]
Hasil kalinya yaitu 
[[48 86 28]
 [46 80 28]]
Hasil transposenya yaitu 
[[48 46]
 [86 80]
 [28 28]]
Rata-ratanya yaitu:  52.666666666666664
Mediannya yaitu: 47.0
